# Blacklist
branches:
  #only:
    #- master

language: c++

jobs:
    include:
        # check code style
        - os: linux
          name: Code Style
          dist: focal # required for clang-format-10
          addons:
              apt:
                  packages:
                      - clang-format-10
          env:
              - CODESTYLE=1
              - CLANG_FORMAT=clang-format-10
        # build
        - os: linux
          name: 'Build'
          addons:
              apt:
                  packages:
                      - build-essential
          env:
              - BUILD=1
before_install:
    - |
        if [ "$BUILD" != "" ]; then
          travis_wait 45 bash ./ci/travis_setup_gcc_arm.sh
          export PATH="/tmp/gcc-arm/bin/:$PATH"
          export GCC_PATH="/tmp/gcc-arm/bin"
        fi

before_script:
    - |
        if [ "$CODESTYLE" != "" ]; then
          $CLANG_FORMAT -version
          ./ci/run-clang-format.py -r modules examples --clang-format-executable $CLANG_FORMAT
        fi

script:
    - |
        if [ "$BUILD" != "" ]; then
          make clean
          make
        fi
